// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVZwsoAs0m14qhJO1eUZaC4Uw1aQsot2I',
    appId: '1:241416293674:web:8eea420c8eadc991f1e253',
    messagingSenderId: '241416293674',
    projectId: 'fir-demo-b1abb',
    authDomain: 'fir-demo-b1abb.firebaseapp.com',
    storageBucket: 'fir-demo-b1abb.appspot.com',
    measurementId: 'G-P4PF2B3X2J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCShMjT5x2Opm91Xo70FgIfDNtStZtSJmk',
    appId: '1:241416293674:android:0051eb372d585c56f1e253',
    messagingSenderId: '241416293674',
    projectId: 'fir-demo-b1abb',
    storageBucket: 'fir-demo-b1abb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBygpOlRrlryWF_TUNkMC6M62ycgDYdCk',
    appId: '1:241416293674:ios:6f9e2b0e26f73f33f1e253',
    messagingSenderId: '241416293674',
    projectId: 'fir-demo-b1abb',
    storageBucket: 'fir-demo-b1abb.appspot.com',
    androidClientId: '241416293674-eqvg2dsa64g4abfuln9gi7aagbbui3vp.apps.googleusercontent.com',
    iosClientId: '241416293674-ki7mtt7f36upnb2p458cha67p8ttre37.apps.googleusercontent.com',
    iosBundleId: 'com.example.hospitelApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBygpOlRrlryWF_TUNkMC6M62ycgDYdCk',
    appId: '1:241416293674:ios:6f9e2b0e26f73f33f1e253',
    messagingSenderId: '241416293674',
    projectId: 'fir-demo-b1abb',
    storageBucket: 'fir-demo-b1abb.appspot.com',
    androidClientId: '241416293674-eqvg2dsa64g4abfuln9gi7aagbbui3vp.apps.googleusercontent.com',
    iosClientId: '241416293674-ki7mtt7f36upnb2p458cha67p8ttre37.apps.googleusercontent.com',
    iosBundleId: 'com.example.hospitelApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3GU8tZMP4rjAsxWBBKdG_QzszMF7GbxE',
    appId: '1:241416293674:web:e0153721d9259630f1e253',
    messagingSenderId: '241416293674',
    projectId: 'fir-demo-b1abb',
    authDomain: 'fir-demo-b1abb.firebaseapp.com',
    storageBucket: 'fir-demo-b1abb.appspot.com',
    measurementId: 'G-QJFJ649BYT',
  );
}
